### ISSUE TITLE
HE Tokens Not Sending [BUG]

### ISSUE THREAD

**Issue by patrickulrich** [stoodkev/hive-keychain-mobile#12]
**Describe the bug**
When I attempt to send HE tokens from the mobile wallet there is not transaction broadcast to Hive.

**Expected behavior**
Wallet should broadcast json transaction for desired transaction.

**Screenshots**
![photo_2020-12-19_19-07-42](https://user-images.githubusercontent.com/3652683/102702158-88bd4900-422d-11eb-8841-70a9d1cc1a57.jpg)

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 11

Keychain will display the successful message regardless of transaction success. I submitted the transaction from an account that doesn't even have ACTIVE keys and it popped up success as well.

**Comment by stoodkev** [comment]
About the behavior with missing private key, I plan to solve it with #4 .
When there is an active key though, the transfer seems to work with no problem on my side. Although successful broadcast doesn't mean successful operation in that case, which can be a bit confusing. Indeed it just checks that the json was broadcasted successfully, but it doesn't mean that it will be processed correctly by Hive Engine (i.e. amount superior to balance). 
I will change the implementation to be similar to the extension and wait for hive-engine confirmation to confirm the transaction, rather than just the blockchain confirmation.
